services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: chinook
      POSTGRES_PASSWORD: chinook
      POSTGRES_DB: chinook
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5008:80"
